### ISSUE TITLE
python mapscript does not unable to find .shp file

### ISSUE THREAD

**Issue by JarekToro** [mapserver/mapserver#5758]
With the given code I am getting a 
```
Traceback (most recent call last):
  File "main.py", line 41, in <module>
    shape = layer.getShape(result)
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2773, in getShape
    return _mapscript.layerObj_getShape(self, record)
IOError: msShapefileOpen(): Unable to access file. (path/data/layer/clu_public_a_ms019_AREAS)
```
In the directory `path/data/layer/`
their is indeed a file clu_public_a_ms019_AREAS.shp
but it looks like it isnt looking for it.

```python
map_obj = mapscript.mapObj("/path/file.map")
extent = map_obj.extent
map_obj.setExtent(x - 1, y - 1, x + 1, y + 1)

point = mapscript.pointObj(x, y)

map_obj.prepareQuery()

layer = map_obj.getLayerByName("lay_name")
layer.queryByPoint(map_obj, point, mapscript.MS_SINGLE, 0)
results = layer.getResults()
returnArray = []

layer.setConnectionType(mapscript.MS_SHAPEFILE, '')
if results:
    layer.open()
    for i in range(results.numresults):
        result = results.getResult(i)
        shape = layer.getShape(result) . <== fails here
        shapeWKT = shape.toWkt()
        shape.free()
        returnArray.append(shapeWKT)

print(returnArray)
```

**Comment by AgSync-Aaron** [comment]
I work with @JarekToro and to add more detail, here is the exact output when running our script in docker.
```
root@77ffea5c13ba:/usr/lib/cgi-bin# ./main.py
Traceback (most recent call last):
  File "./main.py", line 41, in <module>
    shape = layer.getShape(result)
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2773, in getShape
    return _mapscript.layerObj_getShape(self, record)
IOError: msShapefileOpen(): Unable to access file. (�v�/data/CLU-2009/clu_public_a_ms019_AREAS)
```
What's interesting to me is that the parent directory is corrupted in the error message. I thought this might have to do with how docker file shares work, but the text above is the output after I copied the map files directly into the image.

**Comment by geographika** [comment]
Can you double check permissions to that folder for the user running the script?
See https://stackoverflow.com/a/18077831/179520 which may be useful.

**Comment by JarekToro** [comment]
The permissions have been set to allow any user or group
` -rwxrwxrwx 1 www-data www-data ` 
The point of corrupted symbols @AgSync-Aaron brought out is still true
`IOError: msShapefileOpen(): Unable to access file. (?@?/data/CLU-2009/clu_public_a_ms019_AREAS)`

it is also worth noting that everytime the code is ran. The corrupted symbols for the `(?@?/data/CLU-2009/clu_public_a_ms019_AREAS)` is different.

` (???/data/CLU-2009/clu_public_a_ms019_AREAS)`
`(? /data/CLU-2009/clu_public_a_ms019_AREAS)`
`(??(/data/CLU-2009/clu_public_a_ms019_AREAS)`

These are not the only symbols it creates but this gives you the idea.

**Comment by geographika** [comment]
Does the folder name contain unicode characters? If so then this is more likely a Python2/Unicode issue. Try moving the data to a simple folder name like /tmp to see if that helps. 
Also try opening the same file in Python directly (read it with the file name, or` os.path.exists` )

**Comment by JarekToro** [comment]
Thank you, I the data has been moved to `/tmp`
However 
`print(os.path.exists("/tmp/mapdata/data/CLU-2009/clu_public_a_ms019_AREAS.shp"))`
return TRUE

Still receiving same error. We will try to test this on a real vm instead of docker. We have confirm vis sha that the files on prod and the files tested with docker are the same. 

My current theory is maybe the python lib and php lib are handling the lookups differently.

We are able to run similar code on php with success. Also some other errors I've received trying other methods of getting the shape file lead me to believe this as well.

for example 
```python
      shape = mapscript.shapeObj(mapscript.MS_SHAPE_POLYGON)
      layer.resultsGetShape(shape, result.shapeindex)
```
I get other errors
```
 File "main.py", line 43, in <module>
    shape = layer.resultsGetShape(shape, result.shapeindex)
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 2476, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, layerObj, name)
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 74, in _swig_getattr
    return _swig_getattr_nondynamic(self, class_type, name, 0)
  File "/usr/lib/python2.7/dist-packages/mapscript.py", line 69, in _swig_getattr_nondynamic
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'
```

**Comment by JarekToro** [comment]
We are now pretty confidant it is an error in the python version of mapscript. We have ran it out our prod server where the php-mapscript is currently working and we are gettign the same error.

**Comment by geographika** [comment]
I tried the following code with the test Mapfile and shapefiles found in https://github.com/mapserver/mapserver/tree/branch-7-2/tests with MapServer 7.2 and successfully got results. 
Maybe try the following on your server with the same Mapfile and test shapefile?


```python
import mapscript

map_obj = mapscript.mapObj("/mapserver/tests/test.map")
extent = map_obj.extent
x, y = 0.0, 51.5
map_obj.setExtent(x - 1, y - 1, x + 1, y + 1)

point = mapscript.pointObj(x, y)

map_obj.prepareQuery()

layer = map_obj.getLayerByName("POINT")
layer.queryByPoint(map_obj, point, mapscript.MS_SINGLE, 2.0)
results = layer.getResults()
returnArray = []

# following not required if connection type is already a shapefile
layer.setConnectionType(mapscript.MS_SHAPEFILE, '')

if results:
    layer.open()
    for i in range(results.numresults):
        result = results.getResult(i)
        shape = layer.getShape(result)
        shapeWKT = shape.toWKT() # note toWKT not toWkt
        # shape.free() # method does not exist
        returnArray.append(shapeWKT)

print(returnArray)
print("Done!")
```

**Comment by JarekToro** [comment]
Thank you I will give it a shot. In my research It seems that Mapscript 7.0 is not compatible with python 2.7. Is that true?

**Comment by geographika** [comment]
MapScript 7.x is compatible with Python 2.7. Python3 support was only added in the 7.2 release.
