### ISSUE TITLE
mapserv crash with SIZE 0

### ISSUE THREAD

**Issue by jmckenna** [MapServer/MapServer#6503]
- using today's `main`
- mapserv crash with `SIZE 0` set inside a STYLE, instead of the expected message of "Invalid SIZE, must be greater than 0"
  ```
    CLASS
      NAME 'Wetlands'
      EXPRESSION 'Swamp or Marsh'
      STYLE
        COLOR 195 252 255
        OUTLINECOLOR 195 252 255
        SYMBOL 'circle'
        SIZE 0
      END
    END  # CLASS
  END  # LAYER
  ```
- nothing visible through an HTTP request (blank page), but at commandline the correct error message is shown, as well as memory leak details:
```
[Tue Mar 29 19:43:09 2022].779230 loadStyle(): General error message. Invalid SIZE, must be greater than 0 (line 347)
loadStyle(): General error message. Invalid SIZE, must be greater than 0 (line 347) <br>

=================================================================
==367123==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1304 byte(s) in 1 object(s) allocated from:
    #0 0x7fbc22662518 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
    #1 0x7fbc221fec97 in msGrowClassStyles /mapserver/src/MapServer-git-main/mapfile.c:3013
    #2 0x7fbc22200b5c in loadClass /mapserver/src/MapServer-git-main/mapfile.c:3255
    #3 0x7fbc22207a66 in loadLayer /mapserver/src/MapServer-git-main/mapfile.c:3961
    #4 0x7fbc22219297 in loadMapInternal /mapserver/src/MapServer-git-main/mapfile.c:6046
    #5 0x7fbc2221aa00 in msLoadMap /mapserver/src/MapServer-git-main/mapfile.c:6305
    #6 0x55b1aa5a3f53 in main /mapserver/src/MapServer-git-main/map2img.c:158
    #7 0x7fbc1f3a809a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

Indirect leak of 7 byte(s) in 1 object(s) allocated from:
    #0 0x7fbc22662330 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7fbc2202595f in msStrdup /mapserver/src/MapServer-git-main/mapstring.cpp:2291
    #2 0x7fbc221fbb6e in loadStyle /mapserver/src/MapServer-git-main/mapfile.c:2658
    #3 0x7fbc22200cad in loadClass /mapserver/src/MapServer-git-main/mapfile.c:3258
    #4 0x7fbc22207a66 in loadLayer /mapserver/src/MapServer-git-main/mapfile.c:3961
    #5 0x7fbc22219297 in loadMapInternal /mapserver/src/MapServer-git-main/mapfile.c:6046
    #6 0x7fbc2221aa00 in msLoadMap /mapserver/src/MapServer-git-main/mapfile.c:6305
    #7 0x55b1aa5a3f53 in main /mapserver/src/MapServer-git-main/map2img.c:158
    #8 0x7fbc1f3a809a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)

SUMMARY: AddressSanitizer: 1311 byte(s) leaked in 2 allocation(s).
```

- I still have to produce a standalone sample archive to reproduce this issue, but I wanted to report it right away.

**Comment by geographika** [comment]
@jmckenna you could try the with following change:

https://github.com/geographika/mapserver/commit/4aef3069747eb61208d924fda961ffc53d8ae948

**Comment by sdlime** [comment]
Has this been resolved? I'm guessing so but don't want to close the ticket prematurely.
