### ISSUE TITLE
Oddball crash with old version of PostGIS 

### ISSUE THREAD

**Issue by sdlime** [MapServer/MapServer#6910]
Working on migrations from 7.6.5 to 8.0.1 and I'm running into an rare crash with no obvious explanation. Perhaps this should go to mapserver-dev but I'll start here - easier to document the issue. I'm getting a segfault against a single database schema running an old version of PostgreSQL/PostGIS. It's a super simple setup - just drawing polygons. The 7.6.5 version runs fine against the exact same database but is on a separate server.

- Database server is PostgreSQL 9.0.1 with PostGIS 1.5
- 8.0.1 server - PostgreSQL client is 13.6
- 7.6.5 server - PostgreSQL client is 10.10    

Backtrace when running gdb gives:

```
(gdb) bt
#0  0x00007ffff350bcdb in raise () from /lib64/libc.so.6
#1  0x00007ffff350d375 in abort () from /lib64/libc.so.6
#2  0x00007ffff3551b07 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff3559b8a in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff355ba10 in _int_free () from /lib64/libc.so.6
#5  0x00007ffff78d8f21 in msFreeShape (shape=0x7fffffffdd50) at mapprimitive.c:154
#6  0x00007ffff79135ef in msDrawVectorLayer (map=0x6ad800, layer=0x6b8180, image=0x6e5ea0) at mapdraw.c:1114
#7  0x00007ffff7912a4e in msDrawLayer (map=0x6ad800, layer=0x6b8180, image=0x6e5ea0) at mapdraw.c:876
#8  0x00007ffff7911535 in msDrawMap (map=0x6ad800, querymap=0) at mapdraw.c:444
#9  0x000000000040246b in main (argc=5, argv=0x7fffffffe248) at map2img.c:319
```

It feels like an incompatibility issue related to PostGIS but I'm not sure how to best debug. Other 8.0.1 setups against other databases on that same 9.0.1 PostgreSQL server work fine and I've not run into any other problems - it's isolated to the one database. Running against a shapefile version of the data works fine. #stumped

**Comment by sdlime** [comment]
This really seems like a local issue with PostGIS client versions. I'm gonna close it...
